title: Tuende Szalay's website
description: I'm a phonetician working on Australian English.
url: "https://tuendeszalay.github.io/"
theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme
show_downloads: true
