remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Tuende Szalay's website
description: This website will contain  information on liquids.
show_downloads: true
google_analytics: 
